"""
Django settings for neolithic_deities project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r##1o1@$9sjazc&spf(&s29ha!j*@5j$f*dj%gk09#f50lt-+*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'game',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'neolithic_deities.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'neolithic_deities.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'game/static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-hex-updates',
    }
}
# settings.py

HEX_PROPERTIES = ["terrain", "climate", "koeppen", "population_density"]

COLOR_SCHEMES = {
    "koeppen": {
        "domain": list(range(0, 31)),
        "range": [
            "#184a85", 
            "#1c00ff", 
            "#3183ff", 
            "#61b2f3", 
            "#f40000", 
            "#f8a09f", 
            "#f1af00", 
            "#fce163", 
            "#feff00", 
            "#cdce00", 
            "#a0a100", 
            "#abff9b", 
            "#7bd069", 
            "#4aa12d", 
            "#d2ff44", 
            "#83ff48", 
            "#54ce00", 
            "#f500ff", 
            "#c700d2",
            "#9b37a3", 
            "#9e6fa2", 
            "#b6b8ff", 
            "#6a83e5", 
            "#585ac1", 
            "#380095", 
            "#57ffff", 
            "#5cceff", 
            "#2a8889", 
            "#164f6d", 
            "#bbbbbb", 
            "#717170"
        ],
    },
    "terrain": {
        "domain": [
            "Ice", 
            "Water", 
            "Plains", 
            "Mountains", 
            "Chaparral",
            "Extreme Desert",
            "Semi-Desert",
            "Free",
            "Savannah",
            "Woodlands",
            "Tropical Forest",
            "Grassland",
            "Temperate Forest",
            "Steppe-Forest",
            "Boreal Forest",
        ],
        "range": [
            "#bfd1e5", 
            "#64b5f6",
            "#ffe0b2",
            "#bdbdbd", 
            "#a1887f",
            "#d2b48c", 
            "#f5deb3",
            "#ffffff",
            "#c1b23d", 
            "#8bc34a",
            "#388e3c",
            "#d7c55c",
            "#689f38", 
            "#a2d0a5",
            "#2e7d32",
        ],
    },
    "population_density": {
        "domain": [
            0.0,
            0.1,
            0.3,
            0.5,
            0.8,
            1.5,
            1.0,
            2.0,
            5.0,
        ],
        "range": [
            "#000000",
            "#383838",
            "#555555",
            "#717171",
            "#8D8D8D",
            "#aaaaaa",
            "#c6c6c6",
            "#e2e2e2",
            "#ffffff",
        ],
    },
}
